### PR TITLE
This PR resolves #421, #430, #436 , and related to #345, #386, #425, #440

### LINKED ISSUE #421: Hide video recording functionality
We don't support video properly yet, so it should be removed from the recording activity.

### PR DESCRIPTION
**Pull request by lisaslyis**
#345 
- All metadata field keys are now using snake_case
- All file-related values such as file-extension, file-type and meatadata-fields are parameterized

#386 
- New menu item 'wifi sync' is added to the overflow menu and this replaces ftp sync menu
- 'wifi sync' menu starts a new activity which has UI for wifi sync
- 'wifi sync' will allow a sync of all recording and speaker files between two devices over a wifi p2p connection
- In the wifi sync activity,
  a. First two lines show the device information and connection status
  b. The lines below a show the sync result or progress
  c. The main three buttons allow an user to do a wifi sync
  d. Under the buttons, a list of peers can appear if search button is pressed.
- Interaction
  a. Press 'Search' button
  b. Select one of the peer shown in the list under the buttons to create a connection
  c. One of the devices become a server, and sync buttons is only enabled for clients
  d. Clients can press the sync button to start wifi sync
  e. Any user can press the disconnect button, back button or turn off the device to break the connection
- After wifi sync finishes, a summary message pops up in a client device
- Currently, it assumes one-to-one connection.

#440 
- v02 folder is now the default folder for files

### CODE REVIEW

**Comment by stevenbird** [comment]
@lisaslyis does the stale FTP sync code need to be removed still?

**Comment by lisaslyis** [comment]
@stevenbird  It's not removed but hidden now. Will it be okay to remove the whole code of ftp sync?

**Comment by stevenbird** [comment]
Yes, please remove it.

**Comment by lisaslyis** [comment]
Okay, I'll make another PR after removing the previous ftp sync code

**Pull request merged**
